build:
  maxIssues: 100

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'

complexity:
  LongParameterList:
    active: false
  LongMethod:
    active: false
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview', 'ThemePreviews', 'FontSizePreviews', 'DensityPreviews', 'LocalePreviews']
  WildcardImport:
    active: false
