build:
  maxIssues: 100
  excludeCorrectable: false

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'

style:
  WildcardImport:
    active: false
