#name: Create release
#
#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
#
#jobs:
#  create-release:
#    name: Create release
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Check the branch is develop
#        if: endsWith(github.ref, 'develop') == false
#        run: exit -1
#
#      - name: Create release
#        uses: softprops/action-gh-release@v1
