name: Run Detekt

on:
  workflow_call:

jobs:
  run-detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew commands executable
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Move Detekt reports
        run: |
          mkdir detekt_reports
          cd detekt_reports
          mkdir {clean,kotlin_common,kotlin_coroutines,logpecker,platform_android,thirdparty_okhttp,ui_compose,ui_view,webrtc}
          cd ..
          mv clean/build/reports/detekt detekt_reports/clean
          mv kotlin/common/build/reports/detekt detekt_reports/kotlin_common
          mv kotlin/coroutines/build/reports/detekt detekt_reports/kotlin_coroutines
          mv logpecker/build/reports/detekt detekt_reports/logpecker
          mv platform/android/build/reports/detekt detekt_reports/platform_android
          mv thirdparty/okhttp/build/reports/detekt detekt_reports/thirdparty_okhttp
          mv ui/compose/build/reports/detekt detekt_reports/ui_compose
          mv ui/view/build/reports/detekt detekt_reports/ui_view
          mv webrtc/build/reports/detekt detekt_reports/webrtc

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v3
        with:
          name: detekt_reports
          path: detekt_reports

      - name: Upload SARIF reports
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: detekt_reports/clean/detekt/detekt.sarif
          category: Detekt analysis
